import { DiagramConnection, DiagramNode, DiagramType } from '../../core/models/diagram.model';

export interface DiagramTemplate {
  type: DiagramType;
  name: string;
  description: string;
  icon: string;
  nodes: DiagramNode[];
  connections: DiagramConnection[];
}

export const DIAGRAM_TEMPLATES: DiagramTemplate[] = [
  {
    type: 'blank',
    name: 'Blank',
    description: 'Start with an empty canvas.',
    icon: 'fa-regular fa-square',
    nodes: [],
    connections: [],
  },
  {
    type: 'flowchart',
    name: 'Flowchart',
    description: 'Visualize decisions, processes and logic.',
    icon: 'fa-solid fa-code-branch',
    nodes: [
      {
        id: 'flow-start',
        type: 'rounded',
        text: 'Start',
        x: 120,
        y: 120,
        width: 140,
        height: 72,
        background: '#162337',
        color: '#e8f2ff',
        borderColor: '#41b8ff',
        zIndex: 1,
      },
      {
        id: 'flow-process',
        type: 'rectangle',
        text: 'Process',
        x: 360,
        y: 120,
        width: 160,
        height: 80,
        background: '#162337',
        color: '#e8f2ff',
        borderColor: '#41b8ff',
        zIndex: 2,
      },
      {
        id: 'flow-decision',
        type: 'diamond',
        text: 'Decision?',
        x: 620,
        y: 105,
        width: 120,
        height: 120,
        background: '#162337',
        color: '#e8f2ff',
        borderColor: '#8c6cff',
        zIndex: 3,
      },
      {
        id: 'flow-end',
        type: 'rounded',
        text: 'End',
        x: 870,
        y: 120,
        width: 140,
        height: 72,
        background: '#162337',
        color: '#e8f2ff',
        borderColor: '#41b8ff',
        zIndex: 4,
      },
    ],
    connections: [
      {
        id: 'flow-link-1',
        sourceNodeId: 'flow-start',
        targetNodeId: 'flow-process',
        sourceSide: 'right',
        targetSide: 'left',
        type: 'arrow',
        color: '#41b8ff',
      },
      {
        id: 'flow-link-2',
        sourceNodeId: 'flow-process',
        targetNodeId: 'flow-decision',
        sourceSide: 'right',
        targetSide: 'left',
        type: 'arrow',
        color: '#41b8ff',
      },
      {
        id: 'flow-link-3',
        sourceNodeId: 'flow-decision',
        targetNodeId: 'flow-end',
        sourceSide: 'right',
        targetSide: 'left',
        type: 'arrow',
        color: '#41b8ff',
      },
    ],
  },
  {
    type: 'erd',
    name: 'ER Diagram',
    description: 'Model database entities and relationships.',
    icon: 'fa-solid fa-database',
    nodes: [
      {
        id: 'erd-user',
        type: 'rectangle',
        text: 'Users\n────────\nid\nname\nemail',
        x: 150,
        y: 120,
        width: 190,
        height: 150,
        background: '#162337',
        color: '#e8f2ff',
        borderColor: '#45d6a5',
        zIndex: 1,
      },
      {
        id: 'erd-project',
        type: 'rectangle',
        text: 'Projects\n────────\nid\nworkspaceId\nownerId',
        x: 500,
        y: 120,
        width: 200,
        height: 150,
        background: '#162337',
        color: '#e8f2ff',
        borderColor: '#41b8ff',
        zIndex: 2,
      },
      {
        id: 'erd-task',
        type: 'rectangle',
        text: 'Tasks\n────────\nid\nprojectId\nassigneeId',
        x: 850,
        y: 120,
        width: 200,
        height: 150,
        background: '#162337',
        color: '#e8f2ff',
        borderColor: '#8c6cff',
        zIndex: 3,
      },
    ],
    connections: [
      {
        id: 'erd-link-1',
        sourceNodeId: 'erd-user',
        targetNodeId: 'erd-project',
        sourceSide: 'right',
        targetSide: 'left',
        type: 'one-to-many',
        color: '#45d6a5',
      },
      {
        id: 'erd-link-2',
        sourceNodeId: 'erd-project',
        targetNodeId: 'erd-task',
        sourceSide: 'right',
        targetSide: 'left',
        type: 'one-to-many',
        color: '#41b8ff',
      },
    ],
  },
  {
    type: 'architecture',
    name: 'System Architecture',
    description: 'Map application services and system components.',
    icon: 'fa-solid fa-sitemap',
    nodes: [
      {
        id: 'architecture-client',
        type: 'rounded',
        text: 'Client App',
        x: 120,
        y: 180,
        width: 170,
        height: 85,
        background: '#162337',
        color: '#e8f2ff',
        borderColor: '#41b8ff',
        zIndex: 1,
      },
      {
        id: 'architecture-api',
        type: 'rectangle',
        text: 'Application API',
        x: 430,
        y: 180,
        width: 190,
        height: 85,
        background: '#162337',
        color: '#e8f2ff',
        borderColor: '#8c6cff',
        zIndex: 2,
      },
      {
        id: 'architecture-database',
        type: 'rounded',
        text: 'Database',
        x: 760,
        y: 90,
        width: 170,
        height: 85,
        background: '#162337',
        color: '#e8f2ff',
        borderColor: '#45d6a5',
        zIndex: 3,
      },
      {
        id: 'architecture-storage',
        type: 'rounded',
        text: 'Storage',
        x: 760,
        y: 285,
        width: 170,
        height: 85,
        background: '#162337',
        color: '#e8f2ff',
        borderColor: '#f2b94b',
        zIndex: 4,
      },
    ],
    connections: [
      {
        id: 'architecture-link-1',
        sourceNodeId: 'architecture-client',
        targetNodeId: 'architecture-api',
        sourceSide: 'right',
        targetSide: 'left',
        type: 'arrow',
        color: '#41b8ff',
      },
      {
        id: 'architecture-link-2',
        sourceNodeId: 'architecture-api',
        targetNodeId: 'architecture-database',
        sourceSide: 'right',
        targetSide: 'left',
        type: 'arrow',
        color: '#45d6a5',
      },
      {
        id: 'architecture-link-3',
        sourceNodeId: 'architecture-api',
        targetNodeId: 'architecture-storage',
        sourceSide: 'right',
        targetSide: 'left',
        type: 'arrow',
        color: '#f2b94b',
      },
    ],
  },
  {
    type: 'workflow',
    name: 'Project Workflow',
    description: 'Plan work from idea through completion.',
    icon: 'fa-solid fa-list-check',
    nodes: [
      {
        id: 'workflow-idea',
        type: 'rounded',
        text: 'Idea',
        x: 100,
        y: 150,
        width: 150,
        height: 75,
        background: '#162337',
        color: '#e8f2ff',
        borderColor: '#8c6cff',
        zIndex: 1,
      },
      {
        id: 'workflow-planned',
        type: 'rectangle',
        text: 'Planned',
        x: 340,
        y: 150,
        width: 150,
        height: 75,
        background: '#162337',
        color: '#e8f2ff',
        borderColor: '#41b8ff',
        zIndex: 2,
      },
      {
        id: 'workflow-progress',
        type: 'rectangle',
        text: 'In Progress',
        x: 580,
        y: 150,
        width: 160,
        height: 75,
        background: '#162337',
        color: '#e8f2ff',
        borderColor: '#f2b94b',
        zIndex: 3,
      },
      {
        id: 'workflow-review',
        type: 'rectangle',
        text: 'Review',
        x: 830,
        y: 150,
        width: 150,
        height: 75,
        background: '#162337',
        color: '#e8f2ff',
        borderColor: '#ff8f5c',
        zIndex: 4,
      },
      {
        id: 'workflow-done',
        type: 'rounded',
        text: 'Done',
        x: 1070,
        y: 150,
        width: 150,
        height: 75,
        background: '#162337',
        color: '#e8f2ff',
        borderColor: '#45d6a5',
        zIndex: 5,
      },
    ],
    connections: [
      {
        id: 'workflow-link-1',
        sourceNodeId: 'workflow-idea',
        targetNodeId: 'workflow-planned',
        sourceSide: 'right',
        targetSide: 'left',
        type: 'arrow',
        color: '#41b8ff',
      },
      {
        id: 'workflow-link-2',
        sourceNodeId: 'workflow-planned',
        targetNodeId: 'workflow-progress',
        sourceSide: 'right',
        targetSide: 'left',
        type: 'arrow',
        color: '#41b8ff',
      },
      {
        id: 'workflow-link-3',
        sourceNodeId: 'workflow-progress',
        targetNodeId: 'workflow-review',
        sourceSide: 'right',
        targetSide: 'left',
        type: 'arrow',
        color: '#41b8ff',
      },
      {
        id: 'workflow-link-4',
        sourceNodeId: 'workflow-review',
        targetNodeId: 'workflow-done',
        sourceSide: 'right',
        targetSide: 'left',
        type: 'arrow',
        color: '#41b8ff',
      },
    ],
  },
  {
    type: 'user-flow',
    name: 'User Flow',
    description: 'Visualize screens and user decisions.',
    icon: 'fa-solid fa-route',
    nodes: [
      {
        id: 'user-flow-entry',
        type: 'circle',
        text: 'Entry',
        x: 120,
        y: 130,
        width: 100,
        height: 100,
        background: '#162337',
        color: '#e8f2ff',
        borderColor: '#41b8ff',
        zIndex: 1,
      },
      {
        id: 'user-flow-screen',
        type: 'rectangle',
        text: 'Main Screen',
        x: 350,
        y: 140,
        width: 170,
        height: 80,
        background: '#162337',
        color: '#e8f2ff',
        borderColor: '#41b8ff',
        zIndex: 2,
      },
      {
        id: 'user-flow-decision',
        type: 'diamond',
        text: 'Continue?',
        x: 650,
        y: 120,
        width: 120,
        height: 120,
        background: '#162337',
        color: '#e8f2ff',
        borderColor: '#8c6cff',
        zIndex: 3,
      },
      {
        id: 'user-flow-complete',
        type: 'circle',
        text: 'Complete',
        x: 930,
        y: 130,
        width: 100,
        height: 100,
        background: '#162337',
        color: '#e8f2ff',
        borderColor: '#45d6a5',
        zIndex: 4,
      },
    ],
    connections: [
      {
        id: 'user-flow-link-1',
        sourceNodeId: 'user-flow-entry',
        targetNodeId: 'user-flow-screen',
        sourceSide: 'right',
        targetSide: 'left',
        type: 'arrow',
        color: '#41b8ff',
      },
      {
        id: 'user-flow-link-2',
        sourceNodeId: 'user-flow-screen',
        targetNodeId: 'user-flow-decision',
        sourceSide: 'right',
        targetSide: 'left',
        type: 'arrow',
        color: '#41b8ff',
      },
      {
        id: 'user-flow-link-3',
        sourceNodeId: 'user-flow-decision',
        targetNodeId: 'user-flow-complete',
        sourceSide: 'right',
        targetSide: 'left',
        type: 'arrow',
        color: '#45d6a5',
      },
    ],
  },
];
