import { DiagramNodeType } from '../../../../../core/models/diagram.model';
export interface DiagramNodeConfig {
  label: string;
  text: string;
  width: number;
  height: number;
  background: string;
  color: string;
  borderColor: string;
  proportionalResize: boolean;
  canHaveBackground: boolean;
  canHaveBorder: boolean;
  textWidthRatio: number;
  textHeightRatio: number;
}
export const DIAGRAM_NODE_CONFIG: Record<DiagramNodeType, DiagramNodeConfig> = {
  rectangle: {
    label: 'Rectangle',
    text: 'Process',
    width: 150,
    height: 70,
    background: 'var(--surface-2)',
    color: 'var(--text-primary)',
    borderColor: '#536fff',
    proportionalResize: false,
    canHaveBackground: true,
    canHaveBorder: true,
    textWidthRatio: 1,
    textHeightRatio: 1,
  },
  rounded: {
    label: 'Rounded',
    text: 'Step',
    width: 150,
    height: 70,
    background: 'var(--surface-2)',
    color: 'var(--text-primary)',
    borderColor: '#00a8cc',
    proportionalResize: false,
    canHaveBackground: true,
    canHaveBorder: true,
    textWidthRatio: 1,
    textHeightRatio: 1,
  },
  circle: {
    label: 'Circle',
    text: 'Node',
    width: 100,
    height: 100,
    background: 'var(--surface-2)',
    color: 'var(--text-primary)',
    borderColor: '#b959ff',
    proportionalResize: true,
    canHaveBackground: true,
    canHaveBorder: true,
    textWidthRatio: 0.68,
    textHeightRatio: 0.68,
  },
  diamond: {
    label: 'Diamond',
    text: 'Decision',
    width: 110,
    height: 110,
    background: 'var(--surface-2)',
    color: 'var(--text-primary)',
    borderColor: '#e5a524',
    proportionalResize: true,
    canHaveBackground: true,
    canHaveBorder: true,
    textWidthRatio: 0.48,
    textHeightRatio: 0.48,
  },
  text: {
    label: 'Text',
    text: 'Text',
    width: 140,
    height: 60,
    background: 'transparent',
    color: '#36b37e',
    borderColor: 'transparent',
    proportionalResize: false,
    canHaveBackground: false,
    canHaveBorder: false,
    textWidthRatio: 1,
    textHeightRatio: 1,
  },
  ellipse: {
    label: 'Ellipse',
    text: 'Ellipse',
    width: 160,
    height: 90,
    background: 'var(--surface-2)',
    color: 'var(--text-primary)',
    borderColor: '#8b5cf6',
    proportionalResize: false,
    canHaveBackground: true,
    canHaveBorder: true,
    textWidthRatio: 0.72,
    textHeightRatio: 0.65,
  },
  triangle: {
    label: 'Triangle',
    text: 'Triangle',
    width: 130,
    height: 110,
    background: 'var(--surface-2)',
    color: 'var(--text-primary)',
    borderColor: '#ef6c63',
    proportionalResize: true,
    canHaveBackground: true,
    canHaveBorder: true,
    textWidthRatio: 0.55,
    textHeightRatio: 0.45,
  },
  hexagon: {
    label: 'Hexagon',
    text: 'Process',
    width: 160,
    height: 90,
    background: 'var(--surface-2)',
    color: 'var(--text-primary)',
    borderColor: '#14b8a6',
    proportionalResize: false,
    canHaveBackground: true,
    canHaveBorder: true,
    textWidthRatio: 0.72,
    textHeightRatio: 0.7,
  },
  parallelogram: {
    label: 'Input / Output',
    text: 'Input / Output',
    width: 170,
    height: 80,
    background: 'var(--surface-2)',
    color: 'var(--text-primary)',
    borderColor: '#06b6d4',
    proportionalResize: false,
    canHaveBackground: true,
    canHaveBorder: true,
    textWidthRatio: 0.72,
    textHeightRatio: 0.75,
  },
  cylinder: {
    label: 'Database',
    text: 'Database',
    width: 130,
    height: 110,
    background: 'var(--surface-2)',
    color: 'var(--text-primary)',
    borderColor: '#f59e0b',
    proportionalResize: false,
    canHaveBackground: true,
    canHaveBorder: true,
    textWidthRatio: 0.72,
    textHeightRatio: 0.6,
  },
  document: {
    label: 'Document',
    text: 'Document',
    width: 150,
    height: 100,
    background: 'var(--surface-2)',
    color: 'var(--text-primary)',
    borderColor: '#3b82f6',
    proportionalResize: false,
    canHaveBackground: true,
    canHaveBorder: true,
    textWidthRatio: 0.75,
    textHeightRatio: 0.7,
  },
  cloud: {
    label: 'Cloud',
    text: 'Cloud',
    width: 170,
    height: 100,
    background: 'var(--surface-2)',
    color: 'var(--text-primary)',
    borderColor: '#60a5fa',
    proportionalResize: false,
    canHaveBackground: true,
    canHaveBorder: true,
    textWidthRatio: 0.65,
    textHeightRatio: 0.55,
  },
  terminator: {
    label: 'Start / End',
    text: 'Start / End',
    width: 150,
    height: 65,
    background: 'var(--surface-2)',
    color: 'var(--text-primary)',
    borderColor: '#22c55e',
    proportionalResize: false,
    canHaveBackground: true,
    canHaveBorder: true,
    textWidthRatio: 0.78,
    textHeightRatio: 0.8,
  },
  process: {
    label: 'Process',
    text: 'Process',
    width: 160,
    height: 75,
    background: 'var(--surface-2)',
    color: 'var(--text-primary)',
    borderColor: '#536fff',
    proportionalResize: false,
    canHaveBackground: true,
    canHaveBorder: true,
    textWidthRatio: 0.82,
    textHeightRatio: 0.8,
  },
  subprocess: {
    label: 'Subprocess',
    text: 'Subprocess',
    width: 170,
    height: 80,
    background: 'var(--surface-2)',
    color: 'var(--text-primary)',
    borderColor: '#7c83ff',
    proportionalResize: false,
    canHaveBackground: true,
    canHaveBorder: true,
    textWidthRatio: 0.7,
    textHeightRatio: 0.78,
  },
  note: {
    label: 'Note',
    text: 'Note',
    width: 160,
    height: 110,
    background: '#fff3b0',
    color: '#352f12',
    borderColor: '#e5a524',
    proportionalResize: false,
    canHaveBackground: true,
    canHaveBorder: true,
    textWidthRatio: 0.78,
    textHeightRatio: 0.72,
  },
  table: {
    label: 'Table',
    text: '',
    width: 300,
    height: 180,
    background: 'var(--surface-2)',
    color: 'var(--text-primary)',
    borderColor: '#536fff',
    proportionalResize: false,
    canHaveBackground: true,
    canHaveBorder: true,
    textWidthRatio: 1,
    textHeightRatio: 1,
  },
  project: {
    label: 'Project',
    text: 'Project',
    width: 250,
    height: 120,
    background: 'var(--surface-2)',
    color: 'var(--text-primary)',
    borderColor: '#36b37e',
    proportionalResize: false,
    canHaveBackground: true,
    canHaveBorder: true,
    textWidthRatio: 1,
    textHeightRatio: 1,
  },
};
export const DIAGRAM_NODE_TYPES = (
  Object.entries(DIAGRAM_NODE_CONFIG) as [DiagramNodeType, DiagramNodeConfig][]
).map(([value, config]) => ({
  value,
  label: config.label,
}));
